name: Release

on: [workflow_dispatch]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Delete latest tag
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git push origin :refs/tags/latest
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build clienteJar servidorJar --stacktrace
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload Client Asset
        id: upload-client-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/libs/EquipoAlpha-LoveLetter-Cliente.jar
          asset_name: EquipoAlpha-LoveLetter-Cliente.jar
          asset_content_type: application/java-archive
      - name: Upload Server Asset
        id: upload-server-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/libs/EquipoAlpha-LoveLetter-Servidor.jar
          asset_name: EquipoAlpha-LoveLetter-Servidor.jar
          asset_content_type: application/java-archive