name: Release

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: gradle/wrapper-validation-action@v1
      - run: chmod +x gradlew
      - name: Github Release
        run: ./gradlew build github --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}